version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    env_file:
      - .env
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "${MSSQL_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./credentials/db-credentials.json:/run/secrets/db-credentials.json:ro

volumes:
  sql_data:
